[2023-09-27T07:35:38.120-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-09-26T00:00:00+00:00 [queued]>
[2023-09-27T07:35:38.129-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-09-26T00:00:00+00:00 [queued]>
[2023-09-27T07:35:38.129-0400] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-27T07:35:38.144-0400] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): inaccurate> on 2023-09-26 00:00:00+00:00
[2023-09-27T07:35:38.146-0400] {standard_task_runner.py:57} INFO - Started process 11723 to run task
[2023-09-27T07:35:38.150-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2023-09-26T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbp1hh140']
[2023-09-27T07:35:38.151-0400] {standard_task_runner.py:85} INFO - Job 19: Subtask inaccurate
[2023-09-27T07:35:38.191-0400] {task_command.py:415} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2023-09-26T00:00:00+00:00 [running]> on host LAPTOP-F3J2NC12.
[2023-09-27T07:35:38.251-0400] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-09-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-26T00:00:00+00:00'
[2023-09-27T07:35:38.252-0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-27T07:35:38.252-0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2023-09-27T07:35:38.257-0400] {subprocess.py:86} INFO - Output:
[2023-09-27T07:35:38.258-0400] {subprocess.py:93} INFO - inaccurate
[2023-09-27T07:35:38.258-0400] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-27T07:35:38.281-0400] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20230926T000000, start_date=20230927T113538, end_date=20230927T113538
[2023-09-27T07:35:38.322-0400] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-27T07:35:38.332-0400] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
